### ISSUE TITLE
Widget météo ne fonctionne pas ‼️ 

### ISSUE THREAD

**Issue by cxFreeze** [HNTZ/HNTZ.github.io#1]
Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED

**Comment by HNTZ** [comment]
Please show me the steps to reproduce when creating an issue.

**Comment by cxFreeze** [comment]
![20220814_015059](https://user-images.githubusercontent.com/19434393/185103994-70667c51-8002-4cc3-ab8c-1a4f52b1fc6e.jpg)
